name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint:js
